### ISSUE TITLE
support for proxy server

### ISSUE THREAD

**Issue by srinandan** [apigee/istio-mixer-adapter#173]
From k8s, Mixer accesses a few endpoints that are external to k8s. Enterprises will want to secure that with a proxy server. Either document (a native k8s approach) or provide a mechanism to allow the user to specify a proxy server.

**Comment by theganyo** [comment]
A proxy is inserted via the HTTP_PROXY, HTTPS_PROXY, and NO_PROXY environment variables. One way these variables could be added would be to the apigee-adapter container declaration in the apigee-adapter.yaml. 

Example:
```
      containers:
      - name: apigee-adapter
        env:
          - name: HTTP_PROXY
            value: http://http_proxy:port
          - name: HTTPS_PROXY
            value: http://https_proxy:port
          - name: NO_PROXY
            value: 127.0.0.1, localhost
```
