### ISSUE TITLE
Use/Inject Apigee Policies for already deployed Istio enabled Apps

### ISSUE THREAD

**Issue by siddharth-b** [apigee/istio-mixer-adapter#233]
Hi guys, this is not an issue, I need some answers.
Lets says I am working on fully setup instance with Istio installed and Apps(Springboot) deployed with Istio enabled Envoy proxies. So each deployed App has 2 pods, 1 for the App and the other one for EnvoyProxy.

Now I can upgrade existing Istio installation with Apigee mixer using below commands,
>  kubectl -n istio-system set image deployment/istio-telemetry mixer=gcr.io/apigee-api-management-istio/istio-mixer:1.0.4 
> kubectl -n istio-system set image deployment/istio-policy mixer=gcr.io/apigee-api-management-istio/istio-mixer:1.0.4 

How do I inject Apigee policies in these deployed Apps? I tried using below commands with no luck,

>     kubectl apply -f samples/apigee/definitions.yaml
>     kubectl apply -f samples/apigee/handler.yaml
>     kubectl apply -f samples/apigee/rule.yaml

I also ran/installed VirtualService and Gateway YAML.

Any steps/help is appreciated.

Thanks

**Comment by sidd-harth** [comment]
@srinandan  @theganyo 
FYR I am trying to do this in Openshift and these are the YAMLs I am using,
```
apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: helloworld
---  
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
        app: hello
        version: v1
  template:
    metadata:
      labels:
        app: hello
        version: v1
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: -Xms128m -Xmx256m -Djava.net.preferIPv4Stack=true -Djava.security.egd=file:///dev/./urandom
        image: siddharth67/openshift-hello
        imagePullPolicy: IfNotPresent
        name: hello
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        securityContext:
          privileged: false
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: hello-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello
spec:
  hosts:
  - "*"
  gateways:
  - hello-gateway
  http:
  - match:
    - uri:
        exact: /hello
    route:
    - destination:
        host: hello
        port:
          number: 8080
---
```
