### ISSUE TITLE
Service Role Binding property not reading scopes

### ISSUE THREAD

**Issue by Zee-Khan** [apigee/istio-mixer-adapter#234]
I'm trying to create a binding that authorizes certain scopes to access endpoints as follows 
```
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: helloworld-binding
  namespace: default
spec:
  subjects:
  - properties:
      request.auth.claims[scopes]: "READ"
  roleRef:
    kind: ServiceRole
    name: "helloworld-role"
```

The JWT apigee provides returns an array of scopes so it doesn't match.
```
"scopes": [
    "READ"
  ]
```

The property key doesn't accept an array. How do I get it to authorize scopes?
