### ISSUE TITLE
audit and expose configuration

### ISSUE THREAD

**Issue by theganyo** [apigee/istio-mixer-adapter#56]
There are a number of options maintained internally:
1. Evaluate their default values.
2. Determine which to expose, then expose and document them. 

Options:
* general http timeouts
* jwks refresh rate
* jwt acceptable skew
* api key cache expiration
* api key cache eviction interval
* api key max cached entries
* analytics buffer size
* analytics buffer path
* products refresh rate
* quota sync rate
* quota worker pool size
* quota idle bucket sync rate
* quota idle bucket expiration
* quota sync queue size

**Comment by srinandan** [comment]
For 1.0, let's go with

general http timeouts
jwks refresh rate
analytics buffer size
products refresh rate

What is `analytics buffer path`?

**Comment by theganyo** [comment]
That's the path where analytics stages records before uploading.

**Comment by theganyo** [comment]
This is what config will look like with all possible options. The first set is required. The second set is optional and includes their default values:

```
spec:
  apigee_base: https://istioservices.apigee.net/edgemicro
  customer_base: REPLACE ME
  org_name: REPLACE ME
  env_name: REPLACE ME
  key: REPLACE ME
  secret: REPLACE ME

  temp_dir: "/tmp/apigee-istio"
  server_timeout_secs: 60,
  products:
    refresh_rate_mins: 1
  analytics:
    legacy_endpoint: false
    file_limit: 1024
```

(BTW: We don't need the jwks refresh since JWT checking will be done by Istio proxy. I'll be disabling the polling for certs in the adapter.)
